### ISSUE TITLE
Asyncio backends

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [the-wondersmith/celery-aio-pool#7]
Hi, first thanks a ton for this lib the-wondersmith and ShaheedHaque! I'm interested in putting this through my prod env using a Redis backend. I noticed the README uses the amqp protocol, but I don't see an rpc/rabbitmq backend. Is an asyncio backend implementation needed? Happy to contribute a `redis.asyncio` backend.

**Comment by ShaheedHaque** [comment]
@the-wondersmith will correct me if I am wrong, but I think that is simply an example of Celery being setup. Ideally I suppose such a thing would be a useful contribution to Celery itself?

**Comment by Andrew-Chen-Wang** [comment]
I see; I haven't looked through this library enough, but I'm not sure if there is any async calling for results backend, so making an asyncio backend would be useless? Please correct me if I'm wrong.

**Comment by ShaheedHaque** [comment]
@Andrew-Chen-Wang that is indeed my point; this library is just about how workers are run and result backends are elsewhere in Celery.
