### ISSUE TITLE
Pypi out of date with repo

### ISSUE THREAD

**Issue by jgz** [the-wondersmith/celery-aio-pool#8]
Python version was bumped to support 3.11 in the repo but this was never released to pypi.  Still causes errors when trying to install on a python 3.11 project.

**Comment by ShaheedHaque** [comment]
@the-wondersmith Can you kindly do a release or let me know how to do one?

**Comment by the-wondersmith** [comment]
@jgz @ShaheedHaque Apologies for the oversight. I've pushed a new build to PyPi. I'll work on getting @ShaheedHaque push credentials this week, as a guard against similar future oversight 😅

---
Edit (2023-04-02): I've sent you a properly scoped token @ShaheedHaque 😁
